version: '3.7'
services:
  web:
    build: .
    ports:
    - "9000:9000"
    volumes:
    - .:/usr/src/app
  dev-tls:
    build:
      context: .
      dockerfile: ./tls/Dockerfile
    depends_on:
      - web
    links:
      - web
    volumes:
      #      - ./certs:/certs
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - target: 443
        published: 443
        protocol: tcp
